version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - apt update
    - apt install pipx
    - pipx ensurepath
    - pipx ensurepath --global
    - pipx install poetry
    - poetry install

sphinx:
  builder: html
  configuration: doc/source/conf.py
  fail_on_warning: true